---
title: ChaiScript-d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1-x86_64-Linux-Ubuntu-14.04-clang-3.5-AddressSanitizer
permalink: ChaiScript-d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1-x86_64-Linux-Ubuntu-14.04-clang-3.5-AddressSanitizer.html
tags: data
layout: ci_results
date: 2015-05-01 04:44:30
unhandled_failure: false
build_error_count: 0
build_warning_count: 0
package_error_count: 0
package_warning_count: 0
test_count: 346
test_passed_count: 2
repository: ChaiScript/ChaiScript
compiler: clang
compiler_version: 3.5
architecture: 
os: Linux
os_release: Ubuntu-14.04
is_release: false
release_packaged: false
packaging_skipped: true
package_name: 
tag_name: 
commit_sha: d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1
branch_name: parsing_reorg
test_run: true
pull_request_issue_id: ""
pull_request_base_repository: 
pull_request_base_ref: 
device_id: x86_64-Linux-Ubuntu-14.04-clang-3.5-AddressSanitizer
pending: false
analyze_only: false
build_time: 928.426773228
test_time: 21.329142668
package_time: 
install_time: 
results_repository: ChaiScript/ChaiScript-BuildResults
machine_name: jason-VirtualBox
machine_ip: 10.0.2.15
coverage_enabled: false
coverage_pass_limit: 90
coverage_warn_limit: 75
coverage_lines: 0
coverage_total_lines: 0
coverage_functions: 0
coverage_total_functions: 0
coverage_url: 
asset_url: 
---

{
  "build_results": [

  ],
  "test_results": [
    {
      "name": "version_check",
      "status": "failed",
      "time": "1.33695",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/bool_not.chai",
      "status": "failed",
      "time": "1.42882",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/block_start.chai",
      "status": "failed",
      "time": "1.43105",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/assign_const.chai",
      "status": "failed",
      "time": "1.43788",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/bind.chai",
      "status": "failed",
      "time": "1.43551",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/bind2.chai",
      "status": "failed",
      "time": "1.43402",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/break_while.chai",
      "status": "failed",
      "time": "1.42759",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/const_range_test.chai",
      "status": "failed",
      "time": "0.266486",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/char_init.chai",
      "status": "failed",
      "time": "0.391213",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/collate.chai",
      "status": "failed",
      "time": "0.284646",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/compare_lt.chai",
      "status": "failed",
      "time": "0.277405",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/classification.chai",
      "status": "failed",
      "time": "0.286536",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/compare_gt.chai",
      "status": "failed",
      "time": "0.306525",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/concat.chai",
      "status": "failed",
      "time": "0.399286",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_string_double.chai",
      "status": "failed",
      "time": "0.252129",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_int_string.chai",
      "status": "failed",
      "time": "0.256272",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/deep_array_lookup.chai",
      "status": "failed",
      "time": "0.249401",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_string_int.chai",
      "status": "failed",
      "time": "0.275532",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_double_string.chai",
      "status": "failed",
      "time": "0.389965",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/empty.chai",
      "status": "failed",
      "time": "0.251938",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/drop.chai",
      "status": "failed",
      "time": "0.259779",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/dispatch_functions.chai",
      "status": "failed",
      "time": "0.261893",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/equ_shortform.chai",
      "status": "failed",
      "time": "0.367632",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/drop_while.chai",
      "status": "failed",
      "time": "0.480036",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/eval.chai",
      "status": "failed",
      "time": "0.235078",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception.chai",
      "status": "failed",
      "time": "0.235935",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/even.chai",
      "status": "failed",
      "time": "0.244901",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/eval_error.chai",
      "status": "failed",
      "time": "0.265517",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception_finally.chai",
      "status": "failed",
      "time": "0.254704",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception_guards.chai",
      "status": "failed",
      "time": "0.247031",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/foldl.chai",
      "status": "failed",
      "time": "0.241538",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for.chai",
      "status": "failed",
      "time": "0.244636",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each.chai",
      "status": "failed",
      "time": "0.223683",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/float.chai",
      "status": "failed",
      "time": "0.47701",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/filter.chai",
      "status": "failed",
      "time": "0.481017",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each_range.chai",
      "status": "failed",
      "time": "0.238241",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_array_adjacent.chai",
      "status": "failed",
      "time": "0.23938",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each_retro.chai",
      "status": "failed",
      "time": "0.258402",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_introspection.chai",
      "status": "failed",
      "time": "0.350026",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if.chai",
      "status": "failed",
      "time": "0.226852",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/global_const_in_module.chai",
      "status": "failed",
      "time": "0.236715",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/generate_range.chai",
      "status": "failed",
      "time": "0.24144",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_reassignment.chai",
      "status": "failed",
      "time": "0.360698",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_else.chai",
      "status": "failed",
      "time": "0.346739",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/index_operator.chai",
      "status": "failed",
      "time": "0.240921",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/instring_eval.chai",
      "status": "failed",
      "time": "0.23572",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_elseif_else.chai",
      "status": "failed",
      "time": "0.24528",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/inheritance.chai",
      "status": "failed",
      "time": "0.254778",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_elseif.chai",
      "status": "failed",
      "time": "0.366604",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/join.chai",
      "status": "failed",
      "time": "0.23981",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/instring_eval_more.chai",
      "status": "failed",
      "time": "0.248859",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/is_undef.chai",
      "status": "failed",
      "time": "0.247445",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/invalid_function_assignment.chai",
      "status": "failed",
      "time": "0.288728",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/load_module.chai",
      "status": "failed",
      "time": "0.257426",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/invalid_function_reassignment.chai",
      "status": "failed",
      "time": "0.522849",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/list_push_back.chai",
      "status": "failed",
      "time": "0.269006",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/list_push_front.chai",
      "status": "failed",
      "time": "0.268743",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/loop_inner_outer.chai",
      "status": "failed",
      "time": "0.269559",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/lambda.chai",
      "status": "failed",
      "time": "0.287862",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map_access.chai",
      "status": "failed",
      "time": "0.247999",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map.chai",
      "status": "failed",
      "time": "0.249689",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/malformed_inline_map.chai",
      "status": "failed",
      "time": "0.255244",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_inc.chai",
      "status": "failed",
      "time": "0.243384",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_mod.chai",
      "status": "failed",
      "time": "0.23889",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map_inplace_init.chai",
      "status": "failed",
      "time": "0.503504",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_div.chai",
      "status": "failed",
      "time": "0.248424",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_add.chai",
      "status": "failed",
      "time": "0.499867",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_add_mixed.chai",
      "status": "failed",
      "time": "0.27034",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_dec.chai",
      "status": "failed",
      "time": "0.267247",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/max.chai",
      "status": "failed",
      "time": "0.246052",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_negate.chai",
      "status": "failed",
      "time": "0.257361",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_mult.chai",
      "status": "failed",
      "time": "0.258706",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_paren.chai",
      "status": "failed",
      "time": "0.373505",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/min.chai",
      "status": "failed",
      "time": "0.233908",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/method_sugar.chai",
      "status": "failed",
      "time": "0.251132",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/mmd1.chai",
      "status": "failed",
      "time": "0.247153",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_sub.chai",
      "status": "failed",
      "time": "0.506803",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/memberscope.chai",
      "status": "failed",
      "time": "0.477607",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_attr_same_name.chai",
      "status": "failed",
      "time": "0.232566",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/mmd2.chai",
      "status": "failed",
      "time": "0.492006",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/number_formats.chai",
      "status": "failed",
      "time": "0.243506",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_clone.chai",
      "status": "failed",
      "time": "0.230409",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/multiline.chai",
      "status": "failed",
      "time": "0.262981",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_attr.chai",
      "status": "failed",
      "time": "0.258235",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_method_guards.chai",
      "status": "failed",
      "time": "0.241765",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operator_overload2.chai",
      "status": "failed",
      "time": "0.239252",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/odd.chai",
      "status": "failed",
      "time": "0.244978",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_constructor_guards.chai",
      "status": "failed",
      "time": "0.469381",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/pair.chai",
      "status": "failed",
      "time": "0.264713",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operator_overload.chai",
      "status": "failed",
      "time": "0.511953",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_1.chai",
      "status": "failed",
      "time": "0.258154",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operators_float.chai",
      "status": "failed",
      "time": "0.270135",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/pointer_passed_to_constructor.chai",
      "status": "failed",
      "time": "0.281359",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operators_int.chai",
      "status": "failed",
      "time": "0.288208",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range.chai",
      "status": "failed",
      "time": "0.286631",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_eq.chai",
      "status": "failed",
      "time": "0.295904",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_3.chai",
      "status": "failed",
      "time": "0.297334",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_2.chai",
      "status": "failed",
      "time": "0.520176",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_back.chai",
      "status": "failed",
      "time": "0.231102",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_contains.chai",
      "status": "failed",
      "time": "0.227833",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/product.chai",
      "status": "failed",
      "time": "0.524033",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_inplace.chai",
      "status": "failed",
      "time": "0.237683",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/reduce.chai",
      "status": "failed",
      "time": "0.35297",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_find.chai",
      "status": "failed",
      "time": "0.464352",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/return.chai",
      "status": "failed",
      "time": "0.233229",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/retroretro.chai",
      "status": "failed",
      "time": "0.239908",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/retro.chai",
      "status": "failed",
      "time": "0.244556",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/ref_equal.chai",
      "status": "failed",
      "time": "0.266433",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/reflection_test.chai",
      "status": "failed",
      "time": "0.264026",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_concat.chai",
      "status": "failed",
      "time": "0.228084",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_charptr.chai",
      "status": "failed",
      "time": "0.238425",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find.chai",
      "status": "failed",
      "time": "0.23484",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/runtime_error.chai",
      "status": "failed",
      "time": "0.359994",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/shift.chai",
      "status": "failed",
      "time": "0.357528",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_first_not_of.chai",
      "status": "failed",
      "time": "0.246667",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_init.chai",
      "status": "failed",
      "time": "0.23616",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_first_of.chai",
      "status": "failed",
      "time": "0.245768",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_last_not_of.chai",
      "status": "failed",
      "time": "0.256869",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_break.chai",
      "status": "failed",
      "time": "0.255252",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_last_of.chai",
      "status": "failed",
      "time": "0.502952",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_rfind.chai",
      "status": "failed",
      "time": "0.258889",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_default.chai",
      "status": "failed",
      "time": "0.274309",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_literal_access.chai",
      "status": "failed",
      "time": "0.404107",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/sum.chai",
      "status": "failed",
      "time": "0.40013",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/take_while.chai",
      "status": "failed",
      "time": "0.230919",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_empty.chai",
      "status": "failed",
      "time": "0.24452",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_fallthru_and_break.chai",
      "status": "failed",
      "time": "0.239335",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/take.chai",
      "status": "failed",
      "time": "0.251667",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/use.chai",
      "status": "failed",
      "time": "0.239977",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_fallthru.chai",
      "status": "failed",
      "time": "0.486784",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/type_info.chai",
      "status": "failed",
      "time": "0.248676",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_inplace_init.chai",
      "status": "failed",
      "time": "0.23727",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_access.chai",
      "status": "failed",
      "time": "0.268618",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_erase_at.chai",
      "status": "failed",
      "time": "0.265164",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_push_back.chai",
      "status": "failed",
      "time": "0.243643",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_insert_at.chai",
      "status": "failed",
      "time": "0.258899",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_literal_acccess.chai",
      "status": "failed",
      "time": "0.254923",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_of_one.chai",
      "status": "failed",
      "time": "0.480452",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_paren_literal_access.chai",
      "status": "failed",
      "time": "0.47713",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "assign_const.chai",
      "status": "failed",
      "time": "0.233916",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "array_types.chai",
      "status": "failed",
      "time": "0.238896",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_push_empty.chai",
      "status": "failed",
      "time": "0.25007",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/zip.chai",
      "status": "failed",
      "time": "0.369816",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/zip_with.chai",
      "status": "failed",
      "time": "0.367326",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bind2.chai",
      "status": "failed",
      "time": "0.233359",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "break_for.chai",
      "status": "failed",
      "time": "0.237713",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "block_start.chai",
      "status": "failed",
      "time": "0.248199",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bind.chai",
      "status": "failed",
      "time": "0.272453",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bool_not.chai",
      "status": "failed",
      "time": "0.465857",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "break_while.chai",
      "status": "failed",
      "time": "0.261173",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "collate.chai",
      "status": "failed",
      "time": "0.258896",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "char_init.chai",
      "status": "failed",
      "time": "0.269328",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "class.chai",
      "status": "failed",
      "time": "0.38212",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "classification.chai",
      "status": "failed",
      "time": "0.378843",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "const_range_test.chai",
      "status": "failed",
      "time": "0.241877",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "compare_gt.chai",
      "status": "failed",
      "time": "0.249642",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "continue_for.chai",
      "status": "failed",
      "time": "0.238939",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "compare_lt.chai",
      "status": "failed",
      "time": "0.266857",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "concat.chai",
      "status": "failed",
      "time": "0.46771",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "continue_while.chai",
      "status": "failed",
      "time": "0.244594",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_string_int.chai",
      "status": "failed",
      "time": "0.238547",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_double_string.chai",
      "status": "failed",
      "time": "0.249474",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_int_string.chai",
      "status": "failed",
      "time": "0.465383",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_string_double.chai",
      "status": "failed",
      "time": "0.462856",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "divide_by_zero_protection.chai",
      "status": "failed",
      "time": "0.246488",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "dispatch_functions.chai",
      "status": "failed",
      "time": "0.248277",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "drop_while.chai",
      "status": "failed",
      "time": "0.238823",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "deep_array_lookup.chai",
      "status": "failed",
      "time": "0.273471",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "drop.chai",
      "status": "failed",
      "time": "0.265826",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "dynamic_object_dynamic_attrs.chai",
      "status": "failed",
      "time": "0.238696",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "empty.chai",
      "status": "failed",
      "time": "0.236505",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "equ_shortform.chai",
      "status": "failed",
      "time": "0.242817",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval_file.chai",
      "status": "failed",
      "time": "0.256951",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval.chai",
      "status": "failed",
      "time": "0.496834",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval_error.chai",
      "status": "failed",
      "time": "0.488426",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_guards.chai",
      "status": "failed",
      "time": "0.249833",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "even.chai",
      "status": "failed",
      "time": "0.263263",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception.chai",
      "status": "failed",
      "time": "0.289797",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_finally.chai",
      "status": "failed",
      "time": "0.283298",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "filter.chai",
      "status": "failed",
      "time": "0.246553",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "float.chai",
      "status": "failed",
      "time": "0.264116",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_typed.chai",
      "status": "failed",
      "time": "0.273056",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each_range.chai",
      "status": "failed",
      "time": "0.238924",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "foldl.chai",
      "status": "failed",
      "time": "0.507594",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_typed_2.chai",
      "status": "failed",
      "time": "0.51635",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each_retro.chai",
      "status": "failed",
      "time": "0.24266",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_array_adjacent.chai",
      "status": "failed",
      "time": "0.241137",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each.chai",
      "status": "failed",
      "time": "0.280646",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for.chai",
      "status": "failed",
      "time": "0.283426",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_members.chai",
      "status": "failed",
      "time": "0.228238",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_reassignment.chai",
      "status": "failed",
      "time": "0.245175",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_redefinition.chai",
      "status": "failed",
      "time": "0.244116",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "generate_range.chai",
      "status": "failed",
      "time": "0.243448",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_attributes.chai",
      "status": "failed",
      "time": "0.509841",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_introspection.chai",
      "status": "failed",
      "time": "0.505559",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "global_const_in_module.chai",
      "status": "failed",
      "time": "0.243658",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "hashbang.chai",
      "status": "failed",
      "time": "0.240406",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "future.chai",
      "status": "failed",
      "time": "0.383742",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "global_in_script.chai",
      "status": "failed",
      "time": "0.373776",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_elseif.chai",
      "status": "failed",
      "time": "0.2356",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_elseif_else.chai",
      "status": "failed",
      "time": "0.231652",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "index_operator.chai",
      "status": "failed",
      "time": "0.234016",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if.chai",
      "status": "failed",
      "time": "0.267748",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_else.chai",
      "status": "failed",
      "time": "0.466383",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "instring_eval_more.chai",
      "status": "failed",
      "time": "0.235495",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "invalid_function_assignment.chai",
      "status": "failed",
      "time": "0.239831",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "invalid_function_reassignment.chai",
      "status": "failed",
      "time": "0.239084",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "inheritance.chai",
      "status": "failed",
      "time": "0.37012",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "instring_eval.chai",
      "status": "failed",
      "time": "0.367828",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "lambda.chai",
      "status": "failed",
      "time": "0.250788",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "list_push_back.chai",
      "status": "failed",
      "time": "0.249404",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "list_push_front.chai",
      "status": "failed",
      "time": "0.247157",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "is_undef.chai",
      "status": "failed",
      "time": "0.295046",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "join.chai",
      "status": "failed",
      "time": "0.494259",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "loop_inner_outer.chai",
      "status": "failed",
      "time": "0.251066",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "malformed_inline_map.chai",
      "status": "failed",
      "time": "0.248637",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map.chai",
      "status": "failed",
      "time": "0.244107",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "load_module.chai",
      "status": "failed",
      "time": "0.373671",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "logical_short_circuiting.chai",
      "status": "failed",
      "time": "0.371541",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_inplace_init.chai",
      "status": "failed",
      "time": "0.244261",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_add.chai",
      "status": "failed",
      "time": "0.242634",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_add_mixed.chai",
      "status": "failed",
      "time": "0.238013",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_access.chai",
      "status": "failed",
      "time": "0.260824",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_count.chai",
      "status": "failed",
      "time": "0.465299",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_inc.chai",
      "status": "failed",
      "time": "0.240125",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_mod.chai",
      "status": "failed",
      "time": "0.243139",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_mult.chai",
      "status": "failed",
      "time": "0.239955",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_dec.chai",
      "status": "failed",
      "time": "0.381676",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_div.chai",
      "status": "failed",
      "time": "0.379599",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_sub.chai",
      "status": "failed",
      "time": "0.235545",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "max.chai",
      "status": "failed",
      "time": "0.225656",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "member_variable_access.chai",
      "status": "failed",
      "time": "0.230619",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_negate.chai",
      "status": "failed",
      "time": "0.275364",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_paren.chai",
      "status": "failed",
      "time": "0.472327",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "method_sugar.chai",
      "status": "failed",
      "time": "0.243287",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "min.chai",
      "status": "failed",
      "time": "0.235702",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "mmd1.chai",
      "status": "failed",
      "time": "0.234856",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "memberscope.chai",
      "status": "failed",
      "time": "0.386945",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "method_missing.chai",
      "status": "failed",
      "time": "0.383643",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "multiline_oper.chai",
      "status": "failed",
      "time": "0.249539",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "null_object_access.chai",
      "status": "failed",
      "time": "0.249108",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "number_formats.chai",
      "status": "failed",
      "time": "0.233724",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "mmd2.chai",
      "status": "failed",
      "time": "0.277938",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "multiline.chai",
      "status": "failed",
      "time": "0.477563",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_attr_same_name.chai",
      "status": "failed",
      "time": "0.240998",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_clone.chai",
      "status": "failed",
      "time": "0.238468",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_constructor_guards.chai",
      "status": "failed",
      "time": "0.238642",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "number_suffixes.chai",
      "status": "failed",
      "time": "0.379278",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_attr.chai",
      "status": "failed",
      "time": "0.376003",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_overload.chai",
      "status": "failed",
      "time": "0.237648",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_overload2.chai",
      "status": "failed",
      "time": "0.2481",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_scoping.chai",
      "status": "failed",
      "time": "0.239061",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_method_guards.chai",
      "status": "failed",
      "time": "0.27989",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "odd.chai",
      "status": "failed",
      "time": "0.479505",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pair.chai",
      "status": "failed",
      "time": "0.236642",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pass_by_reference.chai",
      "status": "failed",
      "time": "0.23576",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pointer_passed_to_constructor.chai",
      "status": "failed",
      "time": "0.230672",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operators_float.chai",
      "status": "failed",
      "time": "0.367358",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operators_int.chai",
      "status": "failed",
      "time": "0.365074",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_3.chai",
      "status": "failed",
      "time": "0.237473",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_eq.chai",
      "status": "failed",
      "time": "0.239436",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "product.chai",
      "status": "failed",
      "time": "0.244486",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_1.chai",
      "status": "failed",
      "time": "0.281019",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_2.chai",
      "status": "failed",
      "time": "0.482275",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_contains.chai",
      "status": "failed",
      "time": "0.242485",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_find.chai",
      "status": "failed",
      "time": "0.240541",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_inplace.chai",
      "status": "failed",
      "time": "0.232854",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range.chai",
      "status": "failed",
      "time": "0.376379",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_back.chai",
      "status": "failed",
      "time": "0.373943",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "retro.chai",
      "status": "failed",
      "time": "0.257824",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "retroretro.chai",
      "status": "failed",
      "time": "0.274747",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "return.chai",
      "status": "failed",
      "time": "0.271653",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "reduce.chai",
      "status": "failed",
      "time": "0.316769",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "reflection_test.chai",
      "status": "failed",
      "time": "0.516408",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "shift.chai",
      "status": "failed",
      "time": "0.233522",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_charptr.chai",
      "status": "failed",
      "time": "0.240837",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_concat.chai",
      "status": "failed",
      "time": "0.241306",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "runtime_error.chai",
      "status": "failed",
      "time": "0.375432",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "scoping.chai",
      "status": "failed",
      "time": "0.37364",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_first_of.chai",
      "status": "failed",
      "time": "0.245774",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_last_not_of.chai",
      "status": "failed",
      "time": "0.244116",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_last_of.chai",
      "status": "failed",
      "time": "0.245218",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find.chai",
      "status": "failed",
      "time": "0.268464",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_first_not_of.chai",
      "status": "failed",
      "time": "0.468809",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_rfind.chai",
      "status": "failed",
      "time": "0.234101",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_size.chai",
      "status": "failed",
      "time": "0.236113",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_substr.chai",
      "status": "failed",
      "time": "0.238153",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_init.chai",
      "status": "failed",
      "time": "0.370058",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_literal_access.chai",
      "status": "failed",
      "time": "0.368629",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_default.chai",
      "status": "failed",
      "time": "0.231209",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_empty.chai",
      "status": "failed",
      "time": "0.238683",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_fallthru.chai",
      "status": "failed",
      "time": "0.232824",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "sum.chai",
      "status": "failed",
      "time": "0.268256",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_break.chai",
      "status": "failed",
      "time": "0.470538",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "take.chai",
      "status": "failed",
      "time": "0.249551",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "take_while.chai",
      "status": "failed",
      "time": "0.25785",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "temporary_lifetime.chai",
      "status": "failed",
      "time": "0.251414",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_fallthru_and_break.chai",
      "status": "failed",
      "time": "0.388301",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "system_introspection.chai",
      "status": "failed",
      "time": "0.386193",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "use.chai",
      "status": "failed",
      "time": "0.248658",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "user_defined_conversions.chai",
      "status": "failed",
      "time": "0.247347",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "user_defined_conversions_2.chai",
      "status": "failed",
      "time": "0.2444",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "ternary_condition.chai",
      "status": "failed",
      "time": "0.279177",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "type_info.chai",
      "status": "failed",
      "time": "0.480034",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "variable_redefinition.chai",
      "status": "failed",
      "time": "0.239154",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_access.chai",
      "status": "failed",
      "time": "0.23621",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_erase_at.chai",
      "status": "failed",
      "time": "0.234864",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "var_decl.chai",
      "status": "failed",
      "time": "0.363439",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "var_ref_decl.chai",
      "status": "failed",
      "time": "0.360025",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_of_one.chai",
      "status": "failed",
      "time": "0.250944",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_of_suffixed_numbers.chai",
      "status": "failed",
      "time": "0.245212",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_inplace_init.chai",
      "status": "failed",
      "time": "0.256916",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_insert_at.chai",
      "status": "failed",
      "time": "0.274318",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_literal_acccess.chai",
      "status": "failed",
      "time": "0.474145",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_push_empty.chai",
      "status": "failed",
      "time": "0.234044",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "zip.chai",
      "status": "failed",
      "time": "0.242276",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "zip_with.chai",
      "status": "failed",
      "time": "0.240841",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_paren_literal_access.chai",
      "status": "failed",
      "time": "0.371505",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_push_back.chai",
      "status": "failed",
      "time": "0.367053",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Dynamic_Object attributes can be shared with C++",
      "status": "failed",
      "time": "0.163161",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nDynamic_Object attributes can be shared with C++\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:52\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:52: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "52",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Function objects can be created from chaiscript functions",
      "status": "failed",
      "time": "0.159867",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunction objects can be created from chaiscript functions\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:79\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:79: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "79",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "ChaiScript can be created and destroyed on heap",
      "status": "failed",
      "time": "0.157201",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nChaiScript can be created and destroyed on heap\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:94\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:94: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "94",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Test automatic arithmetic conversions",
      "status": "failed",
      "time": "0.154845",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nTest automatic arithmetic conversions\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:126\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:126: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "126",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "C++11 Lambdas Can Be Registered",
      "status": "failed",
      "time": "0.195568",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nC++11 Lambdas Can Be Registered\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:33\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:33: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "33",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Generic exception handling with C++",
      "status": "failed",
      "time": "0.118444",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nGeneric exception handling with C++\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:167\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:167: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "167",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw an int",
      "status": "failed",
      "time": "0.119269",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow an int\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:180\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:180: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "180",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw int or double",
      "status": "failed",
      "time": "0.122462",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow int or double\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:192\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:192: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "192",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw a runtime_error",
      "status": "failed",
      "time": "0.120325",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow a runtime_error\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:204\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:204: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "204",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "No unexpected exceptions leak",
      "status": "failed",
      "time": "0.118134",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nNo unexpected exceptions leak\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:253\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:253: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "253",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw unhandled type",
      "status": "failed",
      "time": "0.127651",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow unhandled type\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:224\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:224: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "224",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Function ordering",
      "status": "failed",
      "time": "0.137334",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunction ordering\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:316\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:316: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "316",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Functor cast",
      "status": "failed",
      "time": "0.139972",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunctor cast\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:339\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:339: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "339",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Set and restore chai state",
      "status": "failed",
      "time": "0.141683",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nSet and restore chai state\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:359\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:359: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "359",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Short comparison with int",
      "status": "failed",
      "time": "0.139002",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nShort comparison with int\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:405\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:405: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "405",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Test lookup of type names",
      "status": "failed",
      "time": "0.135946",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nTest lookup of type names\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:428\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:428: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "428",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Simultaneous ChaiScript tests",
      "status": "failed",
      "time": "0.133244",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nSimultaneous ChaiScript tests\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:454\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:454: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "454",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Utility_Test utility class wrapper",
      "status": "failed",
      "time": "0.133564",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nUtility_Test utility class wrapper\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:488\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:488: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "488",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Object lifetime test 2",
      "status": "failed",
      "time": "0.140286",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject lifetime test 2\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:697\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:697: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "697",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Object copy counts",
      "status": "failed",
      "time": "0.145228",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject copy counts\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:581\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:581: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "581",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Type_Info_Test",
      "status": "passed",
      "time": "0.230283",
      "output": "Size of Type_Info 24\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Boxed_Cast_Test",
      "status": "passed",
      "time": "0.254522",
      "output": null,
      "parsed_errors": [

      ]
    },
    {
      "name": "C_Linkage_Test",
      "status": "failed",
      "time": "0.328023",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Object lifetime tests",
      "status": "failed",
      "time": "0.352926",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject lifetime tests\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:637\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5AS/unittests/compiled_tests.cpp:637: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "637",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Multithreaded_Test",
      "status": "failed",
      "time": "0.18093",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Integer_Literal_Test",
      "status": "failed",
      "time": "0.500061",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "MultiFile_Test",
      "status": "failed",
      "time": "0.180332",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    }
  ],
  "failure": null,
  "package_results": [

  ]
}

