---
title: ChaiScript-d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1-x86_64-Linux-Ubuntu-14.04-clang-3.5
permalink: ChaiScript-d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1-x86_64-Linux-Ubuntu-14.04-clang-3.5.html
tags: data
layout: ci_results
date: 2015-05-01 04:25:28
unhandled_failure: false
build_error_count: 0
build_warning_count: 0
package_error_count: 0
package_warning_count: 0
test_count: 346
test_passed_count: 2
repository: ChaiScript/ChaiScript
compiler: clang
compiler_version: 3.5
architecture: 
os: Linux
os_release: Ubuntu-14.04
is_release: false
release_packaged: false
packaging_skipped: true
package_name: 
tag_name: 
commit_sha: d77921f1b5aa01e8acbb1f5bed2a540ddc6c45e1
branch_name: parsing_reorg
test_run: true
pull_request_issue_id: ""
pull_request_base_repository: 
pull_request_base_ref: 
device_id: x86_64-Linux-Ubuntu-14.04-clang-3.5
pending: false
analyze_only: false
build_time: 116.348288276
test_time: 12.908778996
package_time: 
install_time: 
results_repository: ChaiScript/ChaiScript-BuildResults
machine_name: jason-VirtualBox
machine_ip: 10.0.2.15
coverage_enabled: false
coverage_pass_limit: 90
coverage_warn_limit: 75
coverage_lines: 0
coverage_total_lines: 0
coverage_functions: 0
coverage_total_functions: 0
coverage_url: 
asset_url: 
---

{
  "build_results": [

  ],
  "test_results": [
    {
      "name": "3.x/bool_not.chai",
      "status": "failed",
      "time": "0.215136",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/break_while.chai",
      "status": "failed",
      "time": "0.213791",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/assign_const.chai",
      "status": "failed",
      "time": "0.227248",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/bind.chai",
      "status": "failed",
      "time": "0.226697",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/bind2.chai",
      "status": "failed",
      "time": "0.225628",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "version_check",
      "status": "failed",
      "time": "0.249532",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/block_start.chai",
      "status": "failed",
      "time": "0.241276",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/collate.chai",
      "status": "failed",
      "time": "0.168555",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/char_init.chai",
      "status": "failed",
      "time": "0.173847",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/classification.chai",
      "status": "failed",
      "time": "0.170349",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/compare_gt.chai",
      "status": "failed",
      "time": "0.165269",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/compare_lt.chai",
      "status": "failed",
      "time": "0.181402",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_string_double.chai",
      "status": "failed",
      "time": "0.173845",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_string_int.chai",
      "status": "failed",
      "time": "0.172385",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_double_string.chai",
      "status": "failed",
      "time": "0.184594",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/convert_int_string.chai",
      "status": "failed",
      "time": "0.181241",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/const_range_test.chai",
      "status": "failed",
      "time": "0.187852",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/concat.chai",
      "status": "failed",
      "time": "0.305435",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/dispatch_functions.chai",
      "status": "failed",
      "time": "0.165098",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/equ_shortform.chai",
      "status": "failed",
      "time": "0.170127",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/drop_while.chai",
      "status": "failed",
      "time": "0.17364",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/empty.chai",
      "status": "failed",
      "time": "0.171649",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/drop.chai",
      "status": "failed",
      "time": "0.174974",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception.chai",
      "status": "failed",
      "time": "0.184028",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/deep_array_lookup.chai",
      "status": "failed",
      "time": "0.373192",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/even.chai",
      "status": "failed",
      "time": "0.186185",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/eval.chai",
      "status": "failed",
      "time": "0.192248",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/eval_error.chai",
      "status": "failed",
      "time": "0.189074",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception_guards.chai",
      "status": "failed",
      "time": "0.186548",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/exception_finally.chai",
      "status": "failed",
      "time": "0.206372",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/float.chai",
      "status": "failed",
      "time": "0.191481",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each.chai",
      "status": "failed",
      "time": "0.185158",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/foldl.chai",
      "status": "failed",
      "time": "0.188078",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each_range.chai",
      "status": "failed",
      "time": "0.189044",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for.chai",
      "status": "failed",
      "time": "0.193006",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/filter.chai",
      "status": "failed",
      "time": "0.316901",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/global_const_in_module.chai",
      "status": "failed",
      "time": "0.165332",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/for_each_retro.chai",
      "status": "failed",
      "time": "0.177159",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_array_adjacent.chai",
      "status": "failed",
      "time": "0.175907",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_reassignment.chai",
      "status": "failed",
      "time": "0.172468",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/generate_range.chai",
      "status": "failed",
      "time": "0.168667",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/function_introspection.chai",
      "status": "failed",
      "time": "0.190656",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_else.chai",
      "status": "failed",
      "time": "0.180398",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_elseif.chai",
      "status": "failed",
      "time": "0.177562",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if_elseif_else.chai",
      "status": "failed",
      "time": "0.175002",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/index_operator.chai",
      "status": "failed",
      "time": "0.17819",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/inheritance.chai",
      "status": "failed",
      "time": "0.178816",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/if.chai",
      "status": "failed",
      "time": "0.312432",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/is_undef.chai",
      "status": "failed",
      "time": "0.169756",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/join.chai",
      "status": "failed",
      "time": "0.168069",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/instring_eval_more.chai",
      "status": "failed",
      "time": "0.181711",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/invalid_function_reassignment.chai",
      "status": "failed",
      "time": "0.173833",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/invalid_function_assignment.chai",
      "status": "failed",
      "time": "0.179705",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/instring_eval.chai",
      "status": "failed",
      "time": "0.214428",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/lambda.chai",
      "status": "failed",
      "time": "0.185611",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/malformed_inline_map.chai",
      "status": "failed",
      "time": "0.173291",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/list_push_back.chai",
      "status": "failed",
      "time": "0.186301",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/list_push_front.chai",
      "status": "failed",
      "time": "0.185699",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/load_module.chai",
      "status": "failed",
      "time": "0.181344",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map.chai",
      "status": "failed",
      "time": "0.207208",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_add_mixed.chai",
      "status": "failed",
      "time": "0.214983",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/loop_inner_outer.chai",
      "status": "failed",
      "time": "0.403323",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_add.chai",
      "status": "failed",
      "time": "0.216504",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map_inplace_init.chai",
      "status": "failed",
      "time": "0.221427",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_dec.chai",
      "status": "failed",
      "time": "0.212957",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/map_access.chai",
      "status": "failed",
      "time": "0.245596",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_inc.chai",
      "status": "failed",
      "time": "0.173217",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_div.chai",
      "status": "failed",
      "time": "0.18505",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_mult.chai",
      "status": "failed",
      "time": "0.184454",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_negate.chai",
      "status": "failed",
      "time": "0.189389",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_mod.chai",
      "status": "failed",
      "time": "0.195675",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_paren.chai",
      "status": "failed",
      "time": "0.208501",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/math_sub.chai",
      "status": "failed",
      "time": "0.239469",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/method_sugar.chai",
      "status": "failed",
      "time": "0.231021",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/min.chai",
      "status": "failed",
      "time": "0.234214",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/mmd1.chai",
      "status": "failed",
      "time": "0.228036",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/memberscope.chai",
      "status": "failed",
      "time": "0.357017",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/multiline.chai",
      "status": "failed",
      "time": "0.179233",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/max.chai",
      "status": "failed",
      "time": "0.424977",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_attr.chai",
      "status": "failed",
      "time": "0.170432",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/number_formats.chai",
      "status": "failed",
      "time": "0.176198",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_attr_same_name.chai",
      "status": "failed",
      "time": "0.171965",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/mmd2.chai",
      "status": "failed",
      "time": "0.199868",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operator_overload.chai",
      "status": "failed",
      "time": "0.18722",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_method_guards.chai",
      "status": "failed",
      "time": "0.192035",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_constructor_guards.chai",
      "status": "failed",
      "time": "0.194122",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/odd.chai",
      "status": "failed",
      "time": "0.190194",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operator_overload2.chai",
      "status": "failed",
      "time": "0.187409",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/object_clone.chai",
      "status": "failed",
      "time": "0.319183",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operators_int.chai",
      "status": "failed",
      "time": "0.173922",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/pair.chai",
      "status": "failed",
      "time": "0.175214",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/pointer_passed_to_constructor.chai",
      "status": "failed",
      "time": "0.174982",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_1.chai",
      "status": "failed",
      "time": "0.170402",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_2.chai",
      "status": "failed",
      "time": "0.1753",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/operators_float.chai",
      "status": "failed",
      "time": "0.20624",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_contains.chai",
      "status": "failed",
      "time": "0.191455",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range.chai",
      "status": "failed",
      "time": "0.200423",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/product.chai",
      "status": "failed",
      "time": "0.202169",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_eq.chai",
      "status": "failed",
      "time": "0.20352",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_back.chai",
      "status": "failed",
      "time": "0.205232",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/precedence_3.chai",
      "status": "failed",
      "time": "0.334188",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/retro.chai",
      "status": "failed",
      "time": "0.171394",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/reflection_test.chai",
      "status": "failed",
      "time": "0.173742",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_find.chai",
      "status": "failed",
      "time": "0.185663",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/ref_equal.chai",
      "status": "failed",
      "time": "0.178326",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/reduce.chai",
      "status": "failed",
      "time": "0.181018",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/range_inplace.chai",
      "status": "failed",
      "time": "0.203985",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/shift.chai",
      "status": "failed",
      "time": "0.168744",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/return.chai",
      "status": "failed",
      "time": "0.178455",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/runtime_error.chai",
      "status": "failed",
      "time": "0.173757",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_charptr.chai",
      "status": "failed",
      "time": "0.169673",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_concat.chai",
      "status": "failed",
      "time": "0.170231",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/retroretro.chai",
      "status": "failed",
      "time": "0.306374",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_init.chai",
      "status": "failed",
      "time": "0.172736",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_last_not_of.chai",
      "status": "failed",
      "time": "0.176978",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_first_not_of.chai",
      "status": "failed",
      "time": "0.184089",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_first_of.chai",
      "status": "failed",
      "time": "0.178517",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find_last_of.chai",
      "status": "failed",
      "time": "0.174621",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_find.chai",
      "status": "failed",
      "time": "0.204823",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_rfind.chai",
      "status": "failed",
      "time": "0.183534",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_break.chai",
      "status": "failed",
      "time": "0.173205",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_default.chai",
      "status": "failed",
      "time": "0.17534",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/sum.chai",
      "status": "failed",
      "time": "0.180984",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_empty.chai",
      "status": "failed",
      "time": "0.174565",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_fallthru.chai",
      "status": "failed",
      "time": "0.19897",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/string_literal_access.chai",
      "status": "failed",
      "time": "0.390274",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/take.chai",
      "status": "failed",
      "time": "0.1942",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/use.chai",
      "status": "failed",
      "time": "0.184742",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/take_while.chai",
      "status": "failed",
      "time": "0.194969",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/type_info.chai",
      "status": "failed",
      "time": "0.191178",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/switch_fallthru_and_break.chai",
      "status": "failed",
      "time": "0.217156",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_inplace_init.chai",
      "status": "failed",
      "time": "0.213831",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_insert_at.chai",
      "status": "failed",
      "time": "0.209978",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_access.chai",
      "status": "failed",
      "time": "0.221147",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_of_one.chai",
      "status": "failed",
      "time": "0.209381",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_erase_at.chai",
      "status": "failed",
      "time": "0.338429",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/zip.chai",
      "status": "failed",
      "time": "0.164321",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_literal_acccess.chai",
      "status": "failed",
      "time": "0.383245",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/zip_with.chai",
      "status": "failed",
      "time": "0.173452",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_push_back.chai",
      "status": "failed",
      "time": "0.181404",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_push_empty.chai",
      "status": "failed",
      "time": "0.179009",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "3.x/vector_paren_literal_access.chai",
      "status": "failed",
      "time": "0.201229",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bool_not.chai",
      "status": "failed",
      "time": "0.17095",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bind2.chai",
      "status": "failed",
      "time": "0.17646",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "assign_const.chai",
      "status": "failed",
      "time": "0.185385",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "array_types.chai",
      "status": "failed",
      "time": "0.187008",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "block_start.chai",
      "status": "failed",
      "time": "0.173188",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "break_for.chai",
      "status": "failed",
      "time": "0.172574",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "collate.chai",
      "status": "failed",
      "time": "0.173234",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "char_init.chai",
      "status": "failed",
      "time": "0.180077",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "bind.chai",
      "status": "failed",
      "time": "0.365186",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "classification.chai",
      "status": "failed",
      "time": "0.175543",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "class.chai",
      "status": "failed",
      "time": "0.177469",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "break_while.chai",
      "status": "failed",
      "time": "0.206907",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "continue_while.chai",
      "status": "failed",
      "time": "0.173722",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "concat.chai",
      "status": "failed",
      "time": "0.18554",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "compare_lt.chai",
      "status": "failed",
      "time": "0.189536",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "const_range_test.chai",
      "status": "failed",
      "time": "0.179487",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "compare_gt.chai",
      "status": "failed",
      "time": "0.19386",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "continue_for.chai",
      "status": "failed",
      "time": "0.304431",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "dispatch_functions.chai",
      "status": "failed",
      "time": "0.183312",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_string_int.chai",
      "status": "failed",
      "time": "0.189227",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_double_string.chai",
      "status": "failed",
      "time": "0.196403",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "deep_array_lookup.chai",
      "status": "failed",
      "time": "0.184984",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_string_double.chai",
      "status": "failed",
      "time": "0.191919",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "convert_int_string.chai",
      "status": "failed",
      "time": "0.215841",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "empty.chai",
      "status": "failed",
      "time": "0.196467",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "drop.chai",
      "status": "failed",
      "time": "0.20728",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "divide_by_zero_protection.chai",
      "status": "failed",
      "time": "0.213498",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "dynamic_object_dynamic_attrs.chai",
      "status": "failed",
      "time": "0.199986",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "drop_while.chai",
      "status": "failed",
      "time": "0.204982",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "equ_shortform.chai",
      "status": "failed",
      "time": "0.317497",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval_error.chai",
      "status": "failed",
      "time": "0.183281",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_finally.chai",
      "status": "failed",
      "time": "0.180563",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval.chai",
      "status": "failed",
      "time": "0.195738",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception.chai",
      "status": "failed",
      "time": "0.182423",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "even.chai",
      "status": "failed",
      "time": "0.188178",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "eval_file.chai",
      "status": "failed",
      "time": "0.208707",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "float.chai",
      "status": "failed",
      "time": "0.183148",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_guards.chai",
      "status": "failed",
      "time": "0.192842",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_typed.chai",
      "status": "failed",
      "time": "0.191544",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "exception_typed_2.chai",
      "status": "failed",
      "time": "0.187131",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "filter.chai",
      "status": "failed",
      "time": "0.184954",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_array_adjacent.chai",
      "status": "failed",
      "time": "0.170229",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "foldl.chai",
      "status": "failed",
      "time": "0.360714",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each.chai",
      "status": "failed",
      "time": "0.179245",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each_range.chai",
      "status": "failed",
      "time": "0.174622",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for_each_retro.chai",
      "status": "failed",
      "time": "0.172642",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_attributes.chai",
      "status": "failed",
      "time": "0.167338",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "for.chai",
      "status": "failed",
      "time": "0.200788",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "future.chai",
      "status": "failed",
      "time": "0.172259",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "generate_range.chai",
      "status": "failed",
      "time": "0.174064",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_members.chai",
      "status": "failed",
      "time": "0.184744",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_redefinition.chai",
      "status": "failed",
      "time": "0.177336",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_introspection.chai",
      "status": "failed",
      "time": "0.187554",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_elseif.chai",
      "status": "failed",
      "time": "0.172917",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "function_reassignment.chai",
      "status": "failed",
      "time": "0.373222",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if.chai",
      "status": "failed",
      "time": "0.181504",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "hashbang.chai",
      "status": "failed",
      "time": "0.184737",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "global_in_script.chai",
      "status": "failed",
      "time": "0.189326",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_else.chai",
      "status": "failed",
      "time": "0.179697",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "global_const_in_module.chai",
      "status": "failed",
      "time": "0.215245",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "index_operator.chai",
      "status": "failed",
      "time": "0.173439",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "invalid_function_assignment.chai",
      "status": "failed",
      "time": "0.171352",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "instring_eval.chai",
      "status": "failed",
      "time": "0.183047",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "inheritance.chai",
      "status": "failed",
      "time": "0.184742",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "instring_eval_more.chai",
      "status": "failed",
      "time": "0.175206",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "list_push_back.chai",
      "status": "failed",
      "time": "0.172702",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "if_elseif_else.chai",
      "status": "failed",
      "time": "0.372402",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "is_undef.chai",
      "status": "failed",
      "time": "0.180568",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "list_push_front.chai",
      "status": "failed",
      "time": "0.1741",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "join.chai",
      "status": "failed",
      "time": "0.181656",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "lambda.chai",
      "status": "failed",
      "time": "0.179819",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "invalid_function_reassignment.chai",
      "status": "failed",
      "time": "0.202678",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "loop_inner_outer.chai",
      "status": "failed",
      "time": "0.194482",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "malformed_inline_map.chai",
      "status": "failed",
      "time": "0.193384",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map.chai",
      "status": "failed",
      "time": "0.197069",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "load_module.chai",
      "status": "failed",
      "time": "0.206906",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_access.chai",
      "status": "failed",
      "time": "0.194933",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "logical_short_circuiting.chai",
      "status": "failed",
      "time": "0.326254",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_add.chai",
      "status": "failed",
      "time": "0.187638",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_add_mixed.chai",
      "status": "failed",
      "time": "0.187982",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_count.chai",
      "status": "failed",
      "time": "0.195576",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_dec.chai",
      "status": "failed",
      "time": "0.182542",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_div.chai",
      "status": "failed",
      "time": "0.195379",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "map_inplace_init.chai",
      "status": "failed",
      "time": "0.225518",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_mult.chai",
      "status": "failed",
      "time": "0.172836",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_inc.chai",
      "status": "failed",
      "time": "0.183946",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_negate.chai",
      "status": "failed",
      "time": "0.174716",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_paren.chai",
      "status": "failed",
      "time": "0.176248",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_sub.chai",
      "status": "failed",
      "time": "0.172011",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "math_mod.chai",
      "status": "failed",
      "time": "0.303043",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "method_sugar.chai",
      "status": "failed",
      "time": "0.168911",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "memberscope.chai",
      "status": "failed",
      "time": "0.173324",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "max.chai",
      "status": "failed",
      "time": "0.188354",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "min.chai",
      "status": "failed",
      "time": "0.177275",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "method_missing.chai",
      "status": "failed",
      "time": "0.183093",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "member_variable_access.chai",
      "status": "failed",
      "time": "0.202536",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "multiline.chai",
      "status": "failed",
      "time": "0.171738",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "multiline_oper.chai",
      "status": "failed",
      "time": "0.16987",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "null_object_access.chai",
      "status": "failed",
      "time": "0.168569",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "number_formats.chai",
      "status": "failed",
      "time": "0.175734",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "mmd1.chai",
      "status": "failed",
      "time": "0.185701",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "mmd2.chai",
      "status": "failed",
      "time": "0.305677",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_attr_same_name.chai",
      "status": "failed",
      "time": "0.16831",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_attr.chai",
      "status": "failed",
      "time": "0.171359",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_clone.chai",
      "status": "failed",
      "time": "0.184269",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_constructor_guards.chai",
      "status": "failed",
      "time": "0.178742",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "object_method_guards.chai",
      "status": "failed",
      "time": "0.176165",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "number_suffixes.chai",
      "status": "failed",
      "time": "0.206706",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_overload.chai",
      "status": "failed",
      "time": "0.184221",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_scoping.chai",
      "status": "failed",
      "time": "0.181409",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operator_overload2.chai",
      "status": "failed",
      "time": "0.183694",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operators_int.chai",
      "status": "failed",
      "time": "0.182616",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "operators_float.chai",
      "status": "failed",
      "time": "0.18472",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_3.chai",
      "status": "failed",
      "time": "0.187963",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "odd.chai",
      "status": "failed",
      "time": "0.396961",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pass_by_reference.chai",
      "status": "failed",
      "time": "0.199911",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pointer_passed_to_constructor.chai",
      "status": "failed",
      "time": "0.194293",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_1.chai",
      "status": "failed",
      "time": "0.191868",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_2.chai",
      "status": "failed",
      "time": "0.189783",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "pair.chai",
      "status": "failed",
      "time": "0.216034",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "product.chai",
      "status": "failed",
      "time": "0.19451",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range.chai",
      "status": "failed",
      "time": "0.192075",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_find.chai",
      "status": "failed",
      "time": "0.184362",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "precedence_eq.chai",
      "status": "failed",
      "time": "0.196189",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_back.chai",
      "status": "failed",
      "time": "0.205405",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_contains.chai",
      "status": "failed",
      "time": "0.32476",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "return.chai",
      "status": "failed",
      "time": "0.174382",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "reduce.chai",
      "status": "failed",
      "time": "0.186245",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "range_inplace.chai",
      "status": "failed",
      "time": "0.189463",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "retroretro.chai",
      "status": "failed",
      "time": "0.17727",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "retro.chai",
      "status": "failed",
      "time": "0.178609",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "reflection_test.chai",
      "status": "failed",
      "time": "0.196849",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "scoping.chai",
      "status": "failed",
      "time": "0.166369",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "shift.chai",
      "status": "failed",
      "time": "0.169555",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find.chai",
      "status": "failed",
      "time": "0.179658",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_charptr.chai",
      "status": "failed",
      "time": "0.187198",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_concat.chai",
      "status": "failed",
      "time": "0.182067",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_init.chai",
      "status": "failed",
      "time": "0.174121",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "runtime_error.chai",
      "status": "failed",
      "time": "0.383623",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_last_not_of.chai",
      "status": "failed",
      "time": "0.179142",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_first_not_of.chai",
      "status": "failed",
      "time": "0.189763",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_literal_access.chai",
      "status": "failed",
      "time": "0.171436",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_last_of.chai",
      "status": "failed",
      "time": "0.176388",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_find_first_of.chai",
      "status": "failed",
      "time": "0.207777",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_size.chai",
      "status": "failed",
      "time": "0.177313",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_default.chai",
      "status": "failed",
      "time": "0.178147",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "sum.chai",
      "status": "failed",
      "time": "0.180974",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_break.chai",
      "status": "failed",
      "time": "0.179605",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_rfind.chai",
      "status": "failed",
      "time": "0.189342",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "string_substr.chai",
      "status": "failed",
      "time": "0.301881",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "take.chai",
      "status": "failed",
      "time": "0.166532",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_fallthru_and_break.chai",
      "status": "failed",
      "time": "0.170215",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_empty.chai",
      "status": "failed",
      "time": "0.178169",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "system_introspection.chai",
      "status": "failed",
      "time": "0.169888",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "take_while.chai",
      "status": "failed",
      "time": "0.167781",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "switch_fallthru.chai",
      "status": "failed",
      "time": "0.200705",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "ternary_condition.chai",
      "status": "failed",
      "time": "0.171828",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "user_defined_conversions.chai",
      "status": "failed",
      "time": "0.18019",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "use.chai",
      "status": "failed",
      "time": "0.181661",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "type_info.chai",
      "status": "failed",
      "time": "0.183222",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "user_defined_conversions_2.chai",
      "status": "failed",
      "time": "0.174466",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "temporary_lifetime.chai",
      "status": "failed",
      "time": "0.316837",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "variable_redefinition.chai",
      "status": "failed",
      "time": "0.186357",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "var_ref_decl.chai",
      "status": "failed",
      "time": "0.189",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_erase_at.chai",
      "status": "failed",
      "time": "0.179255",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_access.chai",
      "status": "failed",
      "time": "0.18296",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_inplace_init.chai",
      "status": "failed",
      "time": "0.176371",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "var_decl.chai",
      "status": "failed",
      "time": "0.215372",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_insert_at.chai",
      "status": "failed",
      "time": "0.184376",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_of_one.chai",
      "status": "failed",
      "time": "0.191406",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_push_back.chai",
      "status": "failed",
      "time": "0.184092",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_of_suffixed_numbers.chai",
      "status": "failed",
      "time": "0.188011",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_paren_literal_access.chai",
      "status": "failed",
      "time": "0.186621",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "vector_literal_acccess.chai",
      "status": "failed",
      "time": "0.31679",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "zip.chai",
      "status": "failed",
      "time": "0.149029",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "zip_with.chai",
      "status": "failed",
      "time": "0.158498",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "C++11 Lambdas Can Be Registered",
      "status": "failed",
      "time": "0.156341",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nC++11 Lambdas Can Be Registered\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:33\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:33: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "33",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Dynamic_Object attributes can be shared with C++",
      "status": "failed",
      "time": "0.151979",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nDynamic_Object attributes can be shared with C++\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:52\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:52: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "52",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Function objects can be created from chaiscript functions",
      "status": "failed",
      "time": "0.15093",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunction objects can be created from chaiscript functions\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:79\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:79: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "79",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "vector_push_empty.chai",
      "status": "failed",
      "time": "0.177475",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Test automatic arithmetic conversions",
      "status": "failed",
      "time": "0.0115769",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nTest automatic arithmetic conversions\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:126\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:126: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "126",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "ChaiScript can be created and destroyed on heap",
      "status": "failed",
      "time": "0.014487",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nChaiScript can be created and destroyed on heap\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:94\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:94: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "94",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Generic exception handling with C++",
      "status": "failed",
      "time": "0.0131481",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nGeneric exception handling with C++\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:167\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:167: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "167",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw an int",
      "status": "failed",
      "time": "0.0104961",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow an int\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:180\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:180: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "180",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw a runtime_error",
      "status": "failed",
      "time": "0.0122859",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow a runtime_error\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:204\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:204: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "204",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw int or double",
      "status": "failed",
      "time": "0.0140932",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow int or double\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:192\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:192: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "192",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "No unexpected exceptions leak",
      "status": "failed",
      "time": "0.0173359",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nNo unexpected exceptions leak\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:253\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:253: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "253",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Throw unhandled type",
      "status": "failed",
      "time": "0.0195999",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nThrow unhandled type\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:224\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:224: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "224",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Function ordering",
      "status": "failed",
      "time": "0.0156689",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunction ordering\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:316\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:316: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "316",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Functor cast",
      "status": "failed",
      "time": "0.010638",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFunctor cast\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:339\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:339: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "339",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Test lookup of type names",
      "status": "failed",
      "time": "0.0122461",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nTest lookup of type names\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:428\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:428: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "428",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Short comparison with int",
      "status": "failed",
      "time": "0.0154879",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nShort comparison with int\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:405\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:405: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "405",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Set and restore chai state",
      "status": "failed",
      "time": "0.0170591",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nSet and restore chai state\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:359\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:359: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "359",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Simultaneous ChaiScript tests",
      "status": "failed",
      "time": "0.020025",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nSimultaneous ChaiScript tests\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:454\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:454: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "454",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Utility_Test utility class wrapper",
      "status": "failed",
      "time": "0.0180411",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nUtility_Test utility class wrapper\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:488\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:488: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "488",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Object copy counts",
      "status": "failed",
      "time": "0.017431",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject copy counts\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:581\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:581: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "581",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Type_Info_Test",
      "status": "passed",
      "time": "0.002213",
      "output": "Size of Type_Info 24\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Boxed_Cast_Test",
      "status": "passed",
      "time": "0.0237069",
      "output": null,
      "parsed_errors": [

      ]
    },
    {
      "name": "Object lifetime test 2",
      "status": "failed",
      "time": "0.025497",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject lifetime test 2\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:697\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:697: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "697",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Object lifetime tests",
      "status": "failed",
      "time": "0.0286341",
      "output": "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncompiled_tests is a Catch v1.1 b1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nObject lifetime tests\n-------------------------------------------------------------------------------\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:637\n...............................................................................\n\n/home/jason/CIWork/ci_runs/CS-d77921f1b5-x86_64-C3.5/unittests/compiled_tests.cpp:637: FAILED:\ndue to unexpected exception with message:\n  stod\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 1 | 1 failed\n\n",
      "parsed_errors": [
        {
          "filename": "unittests/compiled_tests.cpp",
          "linenumber": "637",
          "colnumber": 0,
          "messagetype": "error",
          "message": "FAILED:"
        }
      ]
    },
    {
      "name": "Integer_Literal_Test",
      "status": "failed",
      "time": "0.14538",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "Multithreaded_Test",
      "status": "failed",
      "time": "0.159047",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "MultiFile_Test",
      "status": "failed",
      "time": "0.155619",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    },
    {
      "name": "C_Linkage_Test",
      "status": "failed",
      "time": "0.166262",
      "output": "terminate called after throwing an instance of 'std::invalid_argument'\n  what():  stod\n",
      "parsed_errors": [

      ]
    }
  ],
  "failure": null,
  "package_results": [

  ]
}

